# Generated by Django 2.0.4 on 2018-06-10 19:05

from django.db import migrations, models
import django.db.models.deletion
import maw_utils
import submit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orcid', maw_utils.SpaceCharField(blank=True, default='', help_text='Orcid ID for this author', max_length=80, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('surname', maw_utils.SpaceCharField(default='', help_text='Also known as last name or family name', max_length=255)),
                ('given_name', maw_utils.SpaceCharField(help_text='Also known as first name. Please provide at least an initial.', max_length=255)),
                ('create_datetime', models.DateTimeField(auto_now=True, help_text='Author Insertion DateTime', null=True)),
                ('ufdc_user_info', maw_utils.SpaceTextField(blank=True, default='', help_text='UFDC user id info', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_datetime', models.DateTimeField(auto_now=True, help_text='Original file upload dateTime', null=True)),
                ('keywords', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('description', maw_utils.SpaceTextField(default='Your description here.', help_text='Description for this file.')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', maw_utils.SpaceTextField(blank=True, default='', help_text='Your actual note text.', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submittal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_primary', maw_utils.SpaceTextField(default='', help_text='Title of the item you are submitting', max_length=255)),
                ('submittal_datetime', models.DateTimeField(auto_now=True, help_text='Submittal DateTime')),
                ('bibid', maw_utils.SpaceCharField(blank=True, default=None, help_text='This will be automatically assigned in production', max_length=255, null=True)),
                ('publisher', maw_utils.SpaceCharField(blank=True, help_text='This will be automatically assigned in production', max_length=255)),
                ('publication_date', models.DateField(blank=True, help_text='Date of publication.', null=True)),
                ('abstract', maw_utils.SpaceTextField(default='', help_text='Abstract or summary of the content', max_length=255)),
                ('language', maw_utils.SpaceCharField(blank=True, default='', help_text='The actual language.', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittalAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', maw_utils.PositiveIntegerField(default=1, help_text='Primary author should have rank 1. This defines the order of author names in a citation.')),
                ('author', models.ForeignKey(help_text='Author of the associated submittal', on_delete=django.db.models.deletion.CASCADE, to='submit.Author')),
                ('submittal', models.ForeignKey(help_text='Submittal authored by this author', null=True, on_delete=django.db.models.deletion.CASCADE, to='submit.Submittal')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittalFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('download_name', maw_utils.SpaceCharField(default='', help_text='Name to use for this file as part of this submittal', max_length=255, unique=True)),
                ('rank', maw_utils.PositiveIntegerField(default=1, help_text='Rank order of this file within the set of component files of this submittal')),
                ('file', models.ForeignKey(default='', help_text='Component file of the associated submittal', on_delete=django.db.models.deletion.CASCADE, to='submit.File')),
                ('submittal', models.ForeignKey(default='', help_text='Submittal authored by this author', on_delete=django.db.models.deletion.CASCADE, to='submit.Submittal')),
            ],
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', maw_utils.SpaceCharField(default='', help_text='Unique name for this type.', max_length=255, unique=True)),
                ('text', maw_utils.SpaceTextField(default='Your text here.', help_text='Text for this type.')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('upload_datetime', models.DateTimeField(auto_now=True, help_text='Original file upload dateTime', null=True)),
                ('download_name', maw_utils.SpaceCharField(blank=True, help_text='Downlad Name for of this file.', max_length=255, null=True)),
                ('description', maw_utils.SpaceTextField(blank=True, help_text='Optional Description of this file.', null=True)),
                ('location', models.FileField(upload_to=submit.models.upload_location)),
                ('submittal', models.ForeignKey(default='', help_text='Submittal authored by this author', on_delete=django.db.models.deletion.CASCADE, to='submit.Submittal')),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('typemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submit.TypeModel')),
            ],
            bases=('submit.typemodel',),
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('typemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submit.TypeModel')),
            ],
            bases=('submit.typemodel',),
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('typemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submit.TypeModel')),
            ],
            bases=('submit.typemodel',),
        ),
        migrations.CreateModel(
            name='MetadataType',
            fields=[
                ('typemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submit.TypeModel')),
            ],
            bases=('submit.typemodel',),
        ),
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('typemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submit.TypeModel')),
            ],
            bases=('submit.typemodel',),
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('typemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submit.TypeModel')),
            ],
            bases=('submit.typemodel',),
        ),
        migrations.AddField(
            model_name='note',
            name='submittal',
            field=models.ForeignKey(help_text='Id of Submittal authored by this author', null=True, on_delete=django.db.models.deletion.CASCADE, to='submit.Submittal'),
        ),
        migrations.AlterUniqueTogether(
            name='submittalfile',
            unique_together={('submittal', 'file', 'rank')},
        ),
        migrations.AddField(
            model_name='submittalauthor',
            name='affiliation',
            field=models.ForeignKey(help_text='Affiliation of the author at time of initial publication', on_delete=django.db.models.deletion.CASCADE, to='submit.Affiliation'),
        ),
        migrations.AddField(
            model_name='submittal',
            name='license_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='submit.LicenseType'),
        ),
        migrations.AddField(
            model_name='submittal',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.MaterialType'),
        ),
        migrations.AddField(
            model_name='submittal',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.ResourceType'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.NoteType'),
        ),
        migrations.AlterUniqueTogether(
            name='submittalauthor',
            unique_together={('submittal', 'author', 'rank')},
        ),
    ]
