# Generated by Django 2.0.4 on 2018-05-24 12:01

from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orcid_id', models.TextField(blank=True, default='', help_text='Orcid ID for this author', max_length=255, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('surname', models.CharField(blank=True, help_text='Also known as last name or family name)', max_length=255, null=True)),
                ('given_name', models.CharField(blank=True, help_text='Also known as first name)', max_length=255, null=True)),
                ('create_date', models.DateTimeField(auto_now=True, help_text='Author Insertion DateTime', null=True)),
                ('ufdc_user_info', maw_utils.SpaceTextField(blank=True, default='', help_text='UFDC user id info', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solitary_download_name', models.TextField(blank=True, default='', help_text='Name for a solitary downloaded file', max_length=255, null=True)),
                ('submittal_download_name', models.TextField(blank=True, default='', help_text='Name for a downloaded file within a submittal package', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique name for a material type.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique name for a Metadata or template type.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note_type', maw_utils.SpaceCharField(help_text='Brief words to (up to 50 characters) to name note type', max_length=50, unique=True)),
                ('note_description', maw_utils.SpaceTextField(help_text='Description for this type of note up to 500 characters')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Unique name for a resource type or format, per Catalogging.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submittal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_primary', models.TextField(blank=True, default='', help_text='Title of the item you are submitting', max_length=255, null=True)),
                ('bibid', models.CharField(help_text='This will be automatically assigned in production', max_length=255, unique=True)),
                ('publication_date', models.DateField(blank=True, help_text='Date of publication.', null=True)),
                ('abstract', maw_utils.SpaceTextField(help_text='Abstract or summary of the content', max_length=255)),
                ('material_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.MaterialType')),
                ('metadata_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.MetadataType')),
                ('resource_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.ResourceType')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittalAuthor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_id', models.ForeignKey(help_text='Author of the associated submittal', on_delete=django.db.models.deletion.CASCADE, to='submit.Author')),
                ('submittal_id', models.ForeignKey(help_text='Submittal authored by this author', on_delete=django.db.models.deletion.CASCADE, to='submit.Submittal')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittalNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note_text', maw_utils.SpaceTextField(blank=True, default='', help_text='The actual note language.', max_length=255, null=True)),
                ('note_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.NoteType')),
                ('submittal_id', models.ForeignKey(help_text='Id of Submittal authored by this author', on_delete=django.db.models.deletion.CASCADE, to='submit.Submittal')),
            ],
        ),
    ]
