# Generated by Django 2.0.4 on 2018-05-24 13:06

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittal',
            name='language',
            field=maw_utils.SpaceCharField(blank=True, default='', help_text='The actual note language.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submittal',
            name='publisher',
            field=maw_utils.SpaceCharField(blank=True, help_text='This will be automatically assigned in production', max_length=255),
        ),
        migrations.AddField(
            model_name='submittal',
            name='submittal_datetime',
            field=models.DateTimeField(auto_now=True, help_text='Submittal DateTime'),
        ),
        migrations.AlterField(
            model_name='author',
            name='given_name',
            field=maw_utils.SpaceCharField(blank=True, help_text='Also known as first name)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='orcid_id',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Orcid ID for this author', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=maw_utils.SpaceCharField(blank=True, help_text='Also known as last name or family name)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='solitary_download_name',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Name for a solitary downloaded file', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='submittal_download_name',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Name for a downloaded file within a submittal package', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='name',
            field=maw_utils.SpaceCharField(help_text='Unique name for a material type.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='metadatatype',
            name='name',
            field=maw_utils.SpaceCharField(help_text='Unique name for a Metadata or template type.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='name',
            field=maw_utils.SpaceCharField(help_text='Unique name for a resource type or format, per Catalogging.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='bibid',
            field=maw_utils.SpaceCharField(help_text='This will be automatically assigned in production', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='title_primary',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Title of the item you are submitting', max_length=255, null=True),
        ),
    ]
