# Generated by Django 2.0.4 on 2018-05-25 11:08

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='orcid',
            field=maw_utils.SpaceCharField(blank=True, default='', help_text='Orcid ID for this author', max_length=80, null=True),
        ),
    ]
