# Generated by Django 2.0.4 on 2018-05-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0002_auto_20180525_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittal',
            name='author',
        ),
    ]
