# Generated by Django 2.0.4 on 2018-05-25 12:20

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0004_auto_20180525_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittalauthor',
            name='rank',
            field=maw_utils.PositiveIntegerField(default=1, help_text='Primary author should have rank 1. This defines the order of author names in a citation.'),
        ),
        migrations.AlterField(
            model_name='submittalfile',
            name='rank',
            field=maw_utils.PositiveIntegerField(default=1, help_text='Rank order of this file within the set of component files of this submittal'),
        ),
    ]
