# Generated by Django 2.0.4 on 2018-05-25 13:23

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_auto_20180525_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='submittal',
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=maw_utils.SpaceTextField(default='Your description here.', help_text='Description for this file.'),
        ),
    ]
