# Generated by Django 2.0.4 on 2018-05-24 14:25

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0005_auto_20180524_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittal',
            name='bibid',
            field=maw_utils.SpaceCharField(blank=True, help_text='This will be automatically assigned in production', max_length=255, null=True),
        ),
    ]
