# Generated by Django 2.0.4 on 2018-05-24 15:45

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0006_auto_20180524_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialtype',
            name='description',
            field=maw_utils.SpaceTextField(default='Your description here.', help_text='Description for this type of material.'),
        ),
        migrations.AddField(
            model_name='metadatatype',
            name='description',
            field=maw_utils.SpaceTextField(default='Your description here.', help_text='Description for this format of metadata.'),
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='description',
            field=maw_utils.SpaceTextField(default='Your description here.', help_text='Description for this type of resource.'),
        ),
    ]
