# Generated by Django 2.0.2 on 2018-05-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0006_auto_20180525_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='submittal',
            field=models.ForeignKey(help_text='Submittal authored by this author', null=True, on_delete=django.db.models.deletion.CASCADE, to='submit.Submittal'),
        ),
        migrations.AlterField(
            model_name='note',
            name='submittal',
            field=models.ForeignKey(help_text='Id of Submittal authored by this author', null=True, on_delete=django.db.models.deletion.CASCADE, to='submit.Submittal'),
        ),
        migrations.AlterField(
            model_name='submittalauthor',
            name='submittal',
            field=models.ForeignKey(help_text='Submittal authored by this author', null=True, on_delete=django.db.models.deletion.CASCADE, to='submit.Submittal'),
        ),
        migrations.AlterField(
            model_name='submittalfile',
            name='submittal',
            field=models.ForeignKey(help_text='Submittal authored by this author', null=True, on_delete=django.db.models.deletion.CASCADE, to='submit.Submittal'),
        ),
    ]
