# Generated by Django 2.0.2 on 2018-05-27 21:07

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0007_auto_20180527_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='rank',
            field=maw_utils.PositiveIntegerField(default=1, help_text='Rank order of this file within the set of component files of this submittal'),
        ),
    ]
