# Generated by Django 2.0.4 on 2018-05-24 15:55

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0007_auto_20180524_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=maw_utils.SpaceCharField(default='', help_text='Also known as last name or family name)', max_length=255),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='name',
            field=maw_utils.SpaceCharField(default='', help_text='Unique name for a material type.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='metadatatype',
            name='name',
            field=maw_utils.SpaceCharField(default='', help_text='Unique name for a Metadata or template type.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='notetype',
            name='note_description',
            field=maw_utils.SpaceTextField(default='', help_text='Description for this type of note up to 500 characters'),
        ),
        migrations.AlterField(
            model_name='notetype',
            name='note_type',
            field=maw_utils.SpaceCharField(default='', help_text='Brief words to (up to 50 characters) to name note type', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='name',
            field=maw_utils.SpaceCharField(default='', help_text='Unique name for a resource type or format, per Catalogging.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='abstract',
            field=maw_utils.SpaceTextField(default='', help_text='Abstract or summary of the content', max_length=255),
        ),
    ]
