# Generated by Django 2.0.4 on 2018-05-29 12:46

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0008_file_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='file',
            name='solitary_download_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='submittal',
        ),
        migrations.RemoveField(
            model_name='file',
            name='submittal_download_name',
        ),
        migrations.AddField(
            model_name='file',
            name='keywords',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='upload_datetime',
            field=models.DateTimeField(auto_now=True, help_text='Original file upload dateTime', null=True),
        ),
        migrations.AddField(
            model_name='submittalfile',
            name='download_name',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Name for a downloaded file within a submittal package', max_length=255, null=True),
        ),
    ]
