# Generated by Django 2.0.4 on 2018-05-29 14:32

from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0009_auto_20180529_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('typemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submit.TypeModel')),
            ],
            bases=('submit.typemodel',),
        ),
        migrations.RemoveField(
            model_name='submittal',
            name='metadata_type',
        ),
        migrations.AlterField(
            model_name='author',
            name='given_name',
            field=maw_utils.SpaceCharField(default='X.', help_text='Also known as first name. Please provide at least an initial.', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=maw_utils.SpaceCharField(default='', help_text='Also known as last name or family name', max_length=255),
        ),
        migrations.AlterField(
            model_name='submittal',
            name='bibid',
            field=maw_utils.SpaceCharField(blank=True, default=None, help_text='This will be automatically assigned in production', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='submittalfile',
            name='download_name',
            field=maw_utils.SpaceCharField(blank=True, default='', help_text='Name for a downloaded file within a submittal package', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submittal',
            name='license_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='submit.LicenseType'),
        ),
    ]
