# Generated by Django 2.0.4 on 2018-05-29 16:00

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0011_auto_20180529_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittalfile',
            name='download_name',
            field=maw_utils.SpaceCharField(default='', help_text='Name to use for this file as part of this submittal', max_length=255, unique=True),
        ),
    ]
