# Generated by Django 2.0.2 on 2018-05-29 23:39

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0012_auto_20180529_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittal',
            name='title_primary',
            field=maw_utils.SpaceTextField(default='', help_text='Title of the item you are submitting', max_length=255),
        ),
    ]
