# Generated by Django 2.0.2 on 2018-05-29 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0013_auto_20180529_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittalfile',
            name='file',
            field=models.ForeignKey(default='', help_text='Component file of the associated submittal', on_delete=django.db.models.deletion.CASCADE, to='submit.File'),
        ),
        migrations.AlterField(
            model_name='submittalfile',
            name='submittal',
            field=models.ForeignKey(default='', help_text='Submittal authored by this author', on_delete=django.db.models.deletion.CASCADE, to='submit.Submittal'),
        ),
    ]
