# Generated by Django 2.0.4 on 2018-05-30 15:53

from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0014_auto_20180529_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', maw_utils.SpaceTextField(blank=True, help_text='Optional Description of this file.', null=True)),
                ('location', models.FileField(upload_to='submit/')),
                ('submittal', models.ForeignKey(default='', help_text='Submittal authored by this author', on_delete=django.db.models.deletion.CASCADE, to='submit.Submittal')),
            ],
        ),
    ]
