# Generated by Django 2.0.4 on 2018-05-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0015_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='upload_datetime',
            field=models.DateTimeField(auto_now=True, help_text='Original file upload dateTime', null=True),
        ),
    ]
