# Generated by Django 2.0.4 on 2018-06-04 17:05

from django.db import migrations, models
import maw_utils
import submit.models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0016_upload_upload_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='download_name',
            field=maw_utils.SpaceCharField(blank=True, help_text='Downlad Name for of this file.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='location',
            field=models.FileField(upload_to=submit.models.upload_location),
        ),
    ]
