# Generated by Django 2.0.4 on 2018-06-05 14:17

from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0017_auto_20180604_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='xrc_index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='xrc_ionode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', maw_utils.SpaceCharField(default='', help_text='Unique name for this xrconfig including version label .', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='xrc_ofield',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', maw_utils.SpaceCharField(default='', help_text='Unique name for this field for this output relation.', max_length=255, unique=True)),
                ('type', maw_utils.SpaceCharField(default='', help_text='Notes on the type to cast from values in this string field.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='xrc_orel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', maw_utils.SpaceCharField(default='', help_text='Unique name for this output relation for this xrconfig.', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='xrc_reldag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='xrconfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', maw_utils.SpaceCharField(default='', help_text='Unique name for this xrconfig including version label .', max_length=255, unique=True)),
                ('create_datetime', models.DateTimeField(auto_now=True, help_text='Author Insertion DateTime', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='xrc_orel',
            name='xrconfig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.xrconfig'),
        ),
        migrations.AddField(
            model_name='xrc_ofield',
            name='xrc_orel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.xrc_orel'),
        ),
        migrations.AddField(
            model_name='xrc_ionode',
            name='xrconfig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.xrconfig'),
        ),
    ]
