# Generated by Django 2.0.4 on 2018-06-05 17:01

from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0018_auto_20180605_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='xrc_rel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', maw_utils.SpaceCharField(default='', help_text='Unique name for this output relation for this xrconfig.', max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submit.xrc_rel')),
                ('xrconfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submit.xrconfig')),
            ],
            options={
                'ordering': ['xrconfig', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='xrc_orel',
            name='xrconfig',
        ),
        migrations.DeleteModel(
            name='xrc_reldag',
        ),
        migrations.RenameModel(
            old_name='xrc_ofield',
            new_name='xrc_field',
        ),
        migrations.AlterModelOptions(
            name='xrc_field',
            options={'ordering': ['xrc_rel', 'name']},
        ),
        migrations.AddField(
            model_name='xrc_field',
            name='xrc_rel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='submit.xrc_rel'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='xrc_field',
            name='xrc_orel',
        ),
        migrations.DeleteModel(
            name='xrc_orel',
        ),
        migrations.AlterUniqueTogether(
            name='xrc_field',
            unique_together={('xrc_rel', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='xrc_rel',
            unique_together={('xrconfig', 'name')},
        ),
    ]
