# Generated by Django 2.0.4 on 2018-06-07 14:45

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0019_auto_20180605_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='xrc_index',
        ),
        migrations.AddField(
            model_name='xrc_field',
            name='default',
            field=maw_utils.SpaceCharField(default='', help_text='Default value for this field.', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='xrc_field',
            name='is_required',
            field=models.BooleanField(default=True, help_text='True means a value is required.'),
        ),
        migrations.AddField(
            model_name='xrc_field',
            name='is_xml_tag',
            field=models.BooleanField(default=True, help_text='True means the xml_name is an xml_tag. False for an attribute name.'),
        ),
        migrations.AddField(
            model_name='xrc_field',
            name='xml_name',
            field=maw_utils.SpaceCharField(default='', help_text='XML tag or attribute name for this field.', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='xrc_rel',
            name='max_occurs',
            field=models.IntegerField(default=True, help_text='Maximum rows required with this parent.'),
        ),
        migrations.AddField(
            model_name='xrc_rel',
            name='min_occurs',
            field=models.IntegerField(default=True, help_text='Minimum rows required with this parent.'),
        ),
        migrations.AddField(
            model_name='xrc_rel',
            name='order',
            field=models.IntegerField(default=1, help_text='Relative order to output this xml tag within the parent tag.'),
        ),
        migrations.AddField(
            model_name='xrc_rel',
            name='xml_tag',
            field=maw_utils.SpaceCharField(default='', help_text='XML Tag name for one of the items in this relation.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='xrc_field',
            name='type',
            field=maw_utils.SpaceCharField(default='', help_text='Notes on editing and casting a value of this string field to a desired type', max_length=255, unique=True),
        ),
    ]
