# Generated by Django 2.0.7 on 2018-09-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0002_bibvidterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibvid',
            name='count_alto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bibvid',
            name='count_pro',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bibvid',
            name='count_xml',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
