# Generated by Django 2.0.7 on 2018-10-08 18:25

from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0004_x2018subject_x2018thesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bib', maw_utils.SpaceCharField(default='', help_text='Enter alphabetic characters followed by digit characters for a total of 10 characters.', max_length=10, verbose_name='Bibliographic ID')),
                ('vid', maw_utils.SpaceCharField(default='', help_text='Six digit characters with zeroes on the left. ', max_length=10, verbose_name='Bibliographic ID')),
            ],
        ),
        migrations.CreateModel(
            name='BatchSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('import_datetime', models.DateTimeField(auto_now=True, verbose_name='Term search DateTime (UTC)')),
                ('import_user', maw_utils.SpaceCharField(default='name', editable=False, help_text='User who imported this batch', max_length=255, verbose_name='Importing user')),
                ('import_filename', maw_utils.SpaceCharField(default='some_spreadsheet_name', editable=False, help_text='Spreadsheet imported into this batch set of batchitems', max_length=255, verbose_name='Importing user')),
            ],
        ),
        migrations.AddField(
            model_name='batchitem',
            name='batch_set',
            field=models.ForeignKey(help_text='Primary term in thesauri to which this term is related', on_delete=django.db.models.deletion.CASCADE, related_name='related_term', to='dps.BatchSet'),
        ),
        migrations.AlterUniqueTogether(
            name='batchitem',
            unique_together={('batch_set', 'bib', 'vid')},
        ),
    ]
