# Generated by Django 2.0.7 on 2018-10-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0005_auto_20181008_1425'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='batchitem',
            name='batch_set',
        ),
    ]
