# Generated by Django 2.0.7 on 2018-10-08 19:46

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0006_auto_20181008_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='vid',
            field=maw_utils.SpaceCharField(default='', help_text='Six digit characters with zeroes on the left. ', max_length=10, verbose_name='Volume ID'),
        ),
    ]
