# Generated by Django 2.0.7 on 2018-10-08 20:04

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0007_auto_20181008_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='vid',
            field=maw_utils.SpaceCharField(default='', help_text='Five digit characters with zeroes on the left. ', max_length=10, verbose_name='Volume ID'),
        ),
    ]
