# Generated by Django 2.0.7 on 2018-10-09 10:17

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0008_auto_20181008_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='name',
            field=maw_utils.SpaceCharField(default='', help_text='Enter alphabetic characters followed by digit characters for a total of 10 characters.', max_length=10, verbose_name='Bibliographic ID'),
        ),
    ]
