# Generated by Django 2.0.7 on 2018-10-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0009_batchitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='delete',
            field=models.IntegerField(default=0, help_text='1 (delete on next import) or 0 (do not)', verbose_name='Delete on any import?'),
        ),
    ]
