# Generated by Django 2.0.7 on 2018-10-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0010_batchitem_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='batch_set',
            field=models.ForeignKey(blank=True, help_text='Imported BatchSet of which this row is a member.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dps.BatchSet'),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='delete',
            field=models.IntegerField(default=1, help_text='1 (delete on next import of this item) or 0 (do not)', verbose_name='Delete on next import of this item?'),
        ),
        migrations.AlterUniqueTogether(
            name='batchitem',
            unique_together={('batch_set', 'bib', 'vid')},
        ),
    ]
