# Generated by Django 2.0.7 on 2018-10-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0011_auto_20181009_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchitem',
            name='name',
        ),
    ]
