# Generated by Django 2.0.7 on 2018-10-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0012_remove_batchitem_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchitem',
            old_name='bib',
            new_name='bibid',
        ),
        migrations.AlterUniqueTogether(
            name='batchitem',
            unique_together={('batch_set', 'bibid', 'vid')},
        ),
    ]
