# Generated by Django 2.0.7 on 2018-10-09 17:32

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0013_auto_20181009_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchset',
            name='bibid_field',
            field=maw_utils.SpaceCharField(default='BibID', help_text='BibID Spreadshet Field Name', max_length=255, verbose_name='BibID Field Name'),
        ),
        migrations.AddField(
            model_name='batchset',
            name='name',
            field=maw_utils.SpaceCharField(default='BibID', help_text='Up to 255 characters.', max_length=255, verbose_name='Optional Unique Batch Name'),
        ),
        migrations.AddField(
            model_name='batchset',
            name='notes',
            field=maw_utils.SpaceTextField(default='BibID', help_text='Notes about the imported batch of bib-vids.', max_length=255, verbose_name='Notes about the imported batch of bib-vids.'),
        ),
        migrations.AddField(
            model_name='batchset',
            name='vid_field',
            field=maw_utils.SpaceCharField(blank=True, default='VID', help_text='If empty, VID 00001 will be the default database value.', max_length=255, verbose_name='Volume ID Field Name'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='import_filename',
            field=maw_utils.SpaceCharField(default='some_spreadsheet_name', help_text='Filename containing a single spreadsheet to import as a named batch set of bib-vid items', max_length=255, verbose_name='Import Filename'),
        ),
    ]
