# Generated by Django 2.0.7 on 2018-10-09 17:35

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0014_auto_20181009_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchset',
            name='name',
            field=maw_utils.SpaceCharField(default='', help_text='Up to 255 characters.', max_length=255, verbose_name='Optional Unique Batch Name'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='notes',
            field=maw_utils.SpaceTextField(default='', help_text='Notes about the imported batch of bib-vids.', max_length=255, verbose_name='Notes about the imported batch of bib-vids.'),
        ),
    ]
