# Generated by Django 2.0.7 on 2018-10-09 18:15

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0015_auto_20181009_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchset',
            name='item_count',
            field=models.IntegerField(default=0, help_text='Count of import bibvid items from the spreadsheet.', verbose_name='Item Count'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='import_filename',
            field=maw_utils.SpaceCharField(default='some_spreadsheet_name', help_text='Filename containing a single spreadsheet to import saved as tab-separated text file', max_length=255, verbose_name='Import Filename'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='name',
            field=maw_utils.SpaceCharField(db_index=True, default='', help_text='Up to 255 characters.', max_length=255, verbose_name='Optional Unique Batch Name'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='vid_field',
            field=maw_utils.SpaceCharField(blank=True, default='VID', help_text='Spreadsheet Field name for Volume ID (VID). If empty, value 00001 will be set for the database VID value.', max_length=255, verbose_name='Volume ID Field Name'),
        ),
    ]
