# Generated by Django 2.0.7 on 2018-10-11 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0017_auto_20181009_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchset',
            name='import_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='BatchSet Importing DateTime (UTC)'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='import_filename',
            field=maw_utils.SpaceCharField(db_index=True, default='', help_text='Up to 255 characters.', max_length=255, verbose_name='Optional Unique Batch Name'),
        ),

        #migrations.AlterField(
        #    model_name='batchset',
        #    name='import_user',
        #    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        #),

        migrations.AlterField(
            model_name='batchset',
            name='notes',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Optional Notes about the imported batch of bib-vids.', max_length=255, null=True, verbose_name='Notes about the imported batch of bib-vids.'),
        ),
    ]
