# Generated by Django 2.0.7 on 2018-10-11 13:42

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0018_auto_20181011_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchset',
            name='import_user',
        ),
        migrations.AddField(
            model_name='batchset',
            name='import_username',
            field=maw_utils.SpaceCharField(db_index=True, default='', help_text='Up to 255 characters.', max_length=255, verbose_name='Optional Unique Batch Name'),
        ),
    ]
