# Generated by Django 2.0.7 on 2018-10-11 17:57

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0019_auto_20181011_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='bibid_field',
            field=maw_utils.SpaceCharField(default='BibID', help_text="Import file's BibID Field Name", max_length=255, verbose_name='BibID Field Name'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='import_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Importing DateTime (UTC)'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='import_filename',
            field=maw_utils.SpaceCharField(db_index=True, default='', help_text='Up to 255 characters.', max_length=255, verbose_name='Imported File Name'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='import_username',
            field=maw_utils.SpaceCharField(db_index=True, default='', help_text='Up to 255 characters.', max_length=255, verbose_name='User who did the import.'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='item_count',
            field=models.IntegerField(default=0, help_text='Count of import bibvid items from the import.', verbose_name='Item Count'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='name',
            field=maw_utils.SpaceCharField(db_index=True, default='', help_text='Up to 255 characters.', max_length=255, verbose_name='Your Unique Batch Name'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='vid_field',
            field=maw_utils.SpaceCharField(blank=True, default='VID', help_text="Import file's field name for Volume ID (VID). If empty, value 00001 will be set for the VID value.", max_length=255, verbose_name='Volume ID Field Name'),
        ),
    ]
