# Generated by Django 2.0.7 on 2018-10-11 18:34

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0020_auto_20181011_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchitem',
            old_name='count',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='batchset',
            name='bibid_field',
            field=maw_utils.SpaceCharField(default='BibID', help_text="Import file's BibID Field Name", max_length=255, verbose_name='BibID import field'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='vid_field',
            field=maw_utils.SpaceCharField(blank=True, default='VID', help_text="Import file's field name for Volume ID (VID). If empty, value 00001 will be set for the VID value.", max_length=255, verbose_name='Volume ID import field'),
        ),
    ]
