# Generated by Django 2.0.7 on 2018-10-11 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0021_auto_20181011_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchitem',
            old_name='order',
            new_name='row_count',
        ),
        #migrations.AlterField(
        #    model_name='batchitem',
        #    name='id',
        #    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        #),
    ]
