# Generated by Django 2.0.7 on 2018-10-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0022_auto_20181011_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchitem',
            old_name='id',
            new_name='id0',
        ),
    ]
