# Generated by Django 2.0.7 on 2018-10-11 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0023_auto_20181011_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitem',
            name='id0',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
