# Generated by Django 2.0.7 on 2018-10-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0024_auto_20181011_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchitem',
            name='id0',
        ),
    ]
