# Generated by Django 2.0.7 on 2018-10-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0025_remove_batchitem_id0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchitem',
            old_name='id',
            new_name='uuid',
        ),
    ]
