# Generated by Django 2.0.7 on 2018-10-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0026_auto_20181011_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='id',
            field=models.IntegerField(default=0),
        ),
    ]
