# Generated by Django 2.0.7 on 2018-10-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0028_auto_20181011_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchitem',
            name='id',
        ),
    ]
