# Generated by Django 2.0.7 on 2018-10-12 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0029_remove_batchitem_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchset',
            old_name='bibid_field',
            new_name='bibid',
        ),
        migrations.RenameField(
            model_name='batchset',
            old_name='vid_field',
            new_name='vid',
        ),
    ]
