# Generated by Django 2.0.7 on 2018-10-12 14:19

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0030_auto_20181011_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchset',
            name='bibid',
        ),
        migrations.RemoveField(
            model_name='batchset',
            name='vid',
        ),
        migrations.AddField(
            model_name='batchset',
            name='import_bibfield',
            field=maw_utils.SpaceCharField(default='BibID', help_text="Import file's BibID Field Name", max_length=255, verbose_name='Import field with BibID'),
        ),
        migrations.AddField(
            model_name='batchset',
            name='import_vidfield',
            field=maw_utils.SpaceCharField(blank=True, default='VID', help_text="Import file's field name for Volume ID (VID). If empty, value 00001 will be set for the VID value.", max_length=255, verbose_name='Import field with Volume ID'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='item_count',
            field=models.IntegerField(db_index=True, default=0, help_text='Count of import bibvid items from the import.', verbose_name='Item Count'),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='name',
            field=maw_utils.SpaceCharField(db_index=True, default='', help_text='Up to 255 characters.', max_length=255, verbose_name='Custom Unique Batch Name'),
        ),
    ]
