# Generated by Django 2.0.7 on 2018-10-12 15:49

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0032_auto_20181012_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchset',
            name='notes',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Optional Notes about the imported batch of bib-vids.', max_length=3000, null=True, verbose_name='Notes about the imported batch of bib-vids.'),
        ),
    ]
