# Generated by Django 2.0.7 on 2018-10-12 15:52

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0033_auto_20181012_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchset',
            name='name',
            field=maw_utils.SpaceCharField(blank=True, db_index=True, default='', help_text='Up to 255 characters.', max_length=255, null=True, verbose_name='Custom Unique Batch Name'),
        ),
    ]
