# Generated by Django 2.0.7 on 2018-10-17 12:35

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0034_auto_20181012_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchset',
            name='import_username',
            field=maw_utils.SpaceCharField(db_index=True, default='', help_text='Up to 255 characters.', max_length=255, verbose_name='User who did the import'),
        ),
    ]
