# Generated by Django 2.1.2 on 2018-11-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dps', '0035_auto_20181017_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchitem',
            name='batch_set',
            field=models.ForeignKey(blank=True, help_text='BatchSet ID that contains this item.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dps.BatchSet'),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='row_count',
            field=models.IntegerField(default=0, verbose_name='Item'),
        ),
    ]
