# Generated by Django 2.0.3 on 2018-03-16 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hathi_item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_path', models.CharField(max_length=1024)),
                ('state_code', models.IntegerField()),
                ('yaml_status', models.IntegerField()),
            ],
        ),
    ]
