# Generated by Django 2.0.3 on 2018-03-20 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='item_name', max_length=1024)),
                ('modify_date', models.DateTimeField(default=None)),
                ('folder_path', models.CharField(max_length=1024)),
                ('state_code', models.IntegerField()),
                ('yaml_status', models.IntegerField()),
            ],
        ),
    ]
