# Generated by Django 2.0.3 on 2018-03-21 12:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid4', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default='Hathitrust item name', max_length=255, unique=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('folder_path', models.CharField(max_length=1024)),
                ('state_code', models.IntegerField()),
                ('status', models.CharField(choices=[('new', 'new'), ('compiling', 'compiling'), ('packaged', 'package is valid to send'), ('sent', 'sent'), ('evaluated', 'evaluated'), ('recompiling', 'recompiling'), ('done', 'done')], default='new', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hathitrust.Item')),
            ],
        ),
    ]
