# Generated by Django 2.0.3 on 2018-03-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='yaml_status',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('compiling', 'compiling'), ('packaged', 'package is valid to send'), ('sent', 'sent'), ('evaluated', 'evaluated'), ('recompiling', 'recompiling'), ('done', 'done')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Hathitrust item name', max_length=1024),
        ),
    ]
