# Generated by Django 2.0.7 on 2018-11-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalbornyaml',
            name='yaml',
        ),
        migrations.RemoveField(
            model_name='file',
            name='item',
        ),
        migrations.RemoveField(
            model_name='jp2job2',
            name='batch_set',
        ),
        migrations.RemoveField(
            model_name='jp2job2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='printscanyaml',
            name='yaml',
        ),
        migrations.RemoveField(
            model_name='uploadfile',
            name='item',
        ),
        migrations.RemoveField(
            model_name='yaml',
            name='item',
        ),
        migrations.DeleteModel(
            name='DigitalBornYaml',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Jp2Job2',
        ),
        migrations.DeleteModel(
            name='PrintScanYaml',
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
        migrations.DeleteModel(
            name='Yaml',
        ),
    ]
