# Generated by Django 2.0.7 on 2018-11-16 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dps', '0035_auto_20181017_0835'),
        ('subject_app', '0002_auto_20181116_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thesaurus', maw_utils.SpaceTextField(blank=True, default='', help_text='Enter Value for Thesaurus', max_length=2550, null=True, verbose_name='')),
                ('create_datetime', models.DateTimeField(editable=False, null=True, verbose_name='Run Start DateTime (UTC)')),
                ('packages_created', models.IntegerField(default=0, help_text='Number of bib_vid packages created by this job.', null=True)),
                ('jp2_images_processed', models.IntegerField(default=0, help_text='Number of jp2 images packaged by this job.', null=True)),
                ('notes', maw_utils.SpaceTextField(blank=True, default='note', help_text='General notes about this batch job run', max_length=2550, null=True)),
                ('end_datetime', models.DateTimeField(editable=False, null=True, verbose_name='End DateTime (UTC)')),
                ('status', maw_utils.SpaceTextField(blank=True, default='', help_text='Status of ongoing or completed run. Check for status updates as packages are being built.', max_length=2550, null=True, verbose_name='Run Status')),
                ('batch_set', models.ForeignKey(help_text='BatchSet for which to generate SubjectApp JP2 Packages', on_delete=django.db.models.deletion.CASCADE, related_name='subject_app_batch_set', to='dps.BatchSet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_app_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thesaurus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', maw_utils.SpaceTextField(blank=True, default='', help_text='Enter Name for Thesaurus', max_length=2550, null=True, verbose_name='')),
                ('subject_job_id', models.ForeignKey(help_text='Subject ID refrenced from SubjectJob Table', on_delete=django.db.models.deletion.CASCADE, related_name='thesaurus_ref_id', to='subject_app.SubjectJob')),
            ],
        ),
        migrations.RemoveField(
            model_name='jp2job',
            name='batch_set',
        ),
        migrations.RemoveField(
            model_name='jp2job',
            name='user',
        ),
        migrations.DeleteModel(
            name='Jp2Job',
        ),
    ]
