# Generated by Django 2.0.7 on 2018-11-16 20:30

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0003_auto_20181116_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectjob',
            name='thesaurus',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Enter Value for Thesaurus', max_length=2550, null=True, verbose_name='Thesaurus'),
        ),
        migrations.AlterField(
            model_name='thesaurus',
            name='name',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Enter Name for Thesaurus', max_length=2550, null=True, verbose_name='Name'),
        ),
    ]
