# Generated by Django 2.1.2 on 2018-12-06 20:15

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0004_auto_20181116_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectjob',
            name='subject_terms',
            field=maw_utils.SpaceTextField(blank=True, default='', editable=False, max_length=2550, null=True, verbose_name='subject_terms'),
        ),
    ]
