# Generated by Django 2.1.2 on 2018-12-14 18:02

from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0005_subjectjob_subject_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parsed_Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_terms', maw_utils.SpaceTextField(blank=True, default='', editable=False, max_length=2550, null=True, verbose_name='subject_terms')),
                ('subject_job_id', models.ForeignKey(help_text='Subject ID refrenced from SubjectJob Table', on_delete=django.db.models.deletion.CASCADE, related_name='subject_description_id', to='subject_app.SubjectJob')),
            ],
        ),
    ]
