# Generated by Django 2.1.2 on 2018-12-14 19:39

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0006_parsed_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsed_subject',
            name='subject_terms',
        ),
        migrations.AddField(
            model_name='parsed_subject',
            name='subject_term_hinted',
            field=maw_utils.SpaceTextField(blank=True, default='', editable=False, max_length=2550, null=True, verbose_name='subject_terms'),
        ),
        migrations.AddField(
            model_name='parsed_subject',
            name='subject_term_scraped',
            field=maw_utils.SpaceTextField(blank=True, default='', editable=False, max_length=2550, null=True, verbose_name='subject_terms'),
        ),
    ]
