# Generated by Django 2.1.2 on 2018-12-14 20:17

from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0007_auto_20181214_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsed_subject',
            name='subject_job_id',
        ),
        migrations.AddField(
            model_name='parsed_subject',
            name='subject_batchset_id',
            field=models.ForeignKey(default=1, help_text='Subject ID refrenced from SubjectJob Table', on_delete=django.db.models.deletion.CASCADE, related_name='subject_batchset_id', to='subject_app.SubjectJob'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parsed_subject',
            name='subject_term_hinted',
            field=maw_utils.SpaceTextField(blank=True, default='', editable=False, max_length=2550, null=True, verbose_name='subject_term_hinted'),
        ),
        migrations.AlterField(
            model_name='parsed_subject',
            name='subject_term_scraped',
            field=maw_utils.SpaceTextField(blank=True, default='', editable=False, max_length=2550, null=True, verbose_name='subject_term_scraped'),
        ),
    ]
