# Generated by Django 2.1.2 on 2018-12-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0008_auto_20181214_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectjob',
            name='jp2_images_processed',
        ),
        migrations.RemoveField(
            model_name='subjectjob',
            name='packages_created',
        ),
    ]
