# Generated by Django 2.1.2 on 2018-12-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0009_auto_20181221_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectjob',
            name='batch_set',
            field=models.ForeignKey(help_text='BatchSet for which we generate Subject Terms', on_delete=django.db.models.deletion.CASCADE, related_name='subject_app_batch_set', to='dps.BatchSet'),
        ),
    ]
