# Generated by Django 2.1.2 on 2018-12-21 20:13

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0010_auto_20181221_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsed_subject',
            name='subject_type',
            field=maw_utils.SpaceTextField(blank=True, default='', editable=False, max_length=2550, null=True, verbose_name='subject_term_hinted'),
        ),
    ]
