# Generated by Django 2.1.2 on 2018-12-21 21:19

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0011_parsed_subject_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsed_subject',
            name='subject_term_count',
            field=models.IntegerField(default=0, help_text='Total number of hits for the subject term', null=True),
        ),
        migrations.AlterField(
            model_name='parsed_subject',
            name='subject_type',
            field=maw_utils.SpaceTextField(blank=True, default='', editable=False, max_length=2550, null=True, verbose_name='subject_type'),
        ),
    ]
