# Generated by Django 2.0.3 on 2018-03-22 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('accession_number', models.CharField(default='unique accession number', max_length=255)),
                ('agent', models.CharField(choices=[('UF', 'University of Florida'), ('Available', 'Available'), ('Harvard', 'Harvard'), ('NC State', 'North Carolina State University'), ('Other1', 'Some other institutional partner(s)?')], default='Available', max_length=50, verbose_name='Agent')),
                ('agent_modify_date', models.DateTimeField(auto_now=True)),
                ('holding', models.CharField(blank=True, max_length=20)),
                ('reference_type', models.CharField(blank=True, max_length=20)),
                ('authors_primary', models.TextField(blank=True, default='')),
                ('title_primary', models.TextField(default='')),
                ('periodical_full', models.TextField(default='')),
                ('periodical_abbrev', models.TextField(default='')),
                ('pub_year_span', models.CharField(default='2018', max_length=50)),
                ('pub_date_free_from', models.TextField(default='')),
                ('volume', models.CharField(blank=True, max_length=30)),
                ('issue', models.CharField(blank=True, max_length=30)),
                ('start_page', models.CharField(blank=True, max_length=30)),
                ('other_pages', models.CharField(blank=True, max_length=30)),
                ('keywords', models.TextField(blank=True, default='')),
                ('abstract', models.TextField(blank=True, default='')),
                ('personal_notes', models.TextField(blank=True, default='')),
                ('authors_secondary', models.TextField(blank=True, default='')),
                ('title_secondary', models.TextField(blank=True, default='')),
                ('edition', models.CharField(blank=True, default='', max_length=80)),
                ('publisher', models.CharField(blank=True, default='', max_length=255)),
                ('authors_tertiary', models.TextField(blank=True, default='')),
                ('authors_quaternary', models.TextField(blank=True, default='')),
                ('authors_quinary', models.TextField(blank=True, default='')),
                ('titles_tertiary', models.TextField(blank=True, default='')),
                ('isbn_issn', models.CharField(blank=True, max_length=255, verbose_name='ISSN/ISBN')),
                ('availability', models.TextField(blank=True, default='')),
                ('author_address', models.TextField(blank=True, default='', verbose_name='Author/Address')),
                ('language', models.TextField(blank=True, default='')),
                ('classification', models.TextField(blank=True, default='')),
                ('original_foreign_title', models.TextField(blank=True, default='')),
                ('links', models.TextField(blank=True, default='')),
                ('doi', models.TextField(blank=True, default='')),
                ('pmid', models.TextField(blank=True, default='')),
                ('pmcid', models.TextField(blank=True, default='')),
                ('call_number', models.TextField(blank=True, default='')),
                ('database', models.TextField(blank=True, default='')),
                ('data_source', models.TextField(blank=True, default='')),
                ('identifying_phrase', models.TextField(blank=True, default='')),
                ('retrieved_date', models.CharField(blank=True, max_length=255)),
                ('user_1', models.TextField(blank=True, default='')),
                ('user_2', models.TextField(blank=True, default='')),
                ('user_3', models.TextField(blank=True, default='')),
                ('user_4', models.TextField(blank=True, default='')),
                ('user_5', models.TextField(blank=True, default='')),
                ('user_6', models.TextField(blank=True, default='')),
                ('user_7', models.TextField(blank=True, default='')),
                ('user_8', models.TextField(blank=True, default='')),
                ('user_9', models.TextField(blank=True, default='')),
                ('user_10', models.TextField(blank=True, default='')),
                ('user_11', models.TextField(blank=True, default='')),
                ('user_12', models.TextField(blank=True, default='')),
                ('user_13', models.TextField(blank=True, default='')),
                ('user_14', models.TextField(blank=True, default='')),
                ('user_15', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('place_of_publication', models.CharField(blank=True, max_length=255)),
                ('link_url', models.URLField(blank=True, null=True)),
                ('edition_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('sub_file_database', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub file/database')),
            ],
        ),
        migrations.CreateModel(
            name='Item_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuba_libro.Item')),
            ],
        ),
    ]
