# Generated by Django 2.0.3 on 2018-03-21 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('authors', models.CharField(default='', max_length=255)),
                ('title', models.TextField(default='', max_length=2048)),
                ('pub_year', models.IntegerField()),
                ('modify_date', models.DateField(editable=False)),
                ('notes', models.TextField(default='', max_length=2048)),
                ('place_of_publication', models.TextField()),
                ('link_url', models.URLField()),
                ('edition_url', models.URLField()),
                ('url', models.URLField()),
                ('sub_file_database', models.TextField(verbose_name='Sub file/database')),
                ('publisher', models.TextField()),
                ('claimant', models.CharField(choices=[('UF', 'University of Florida'), ('', 'Available'), ('Harvard', 'Harvard'), ('NC State', 'North Carolina State University'), ('Other1', 'Some other institutional partner(s)?')], default='Available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuba_libro.Item')),
            ],
        ),
    ]
