# Generated by Django 2.0.3 on 2018-03-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='authors',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='claimant',
            field=models.CharField(choices=[('UF', 'University of Florida'), ('Available', 'Available'), ('Harvard', 'Harvard'), ('NC State', 'North Carolina State University'), ('Other1', 'Some other institutional partner(s)?')], default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='place_of_publication',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='publisher',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_file_database',
            field=models.TextField(max_length=255, verbose_name='Sub file/database'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(default='', max_length=255),
        ),
    ]
