# Generated by Django 2.0.3 on 2018-03-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='issue',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='other_pages',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='periodical_abbrev',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='periodical_full',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date_free_from',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_page',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='title_primary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='volume',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
