# Generated by Django 2.0.3 on 2018-03-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0002_auto_20180321_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='authors',
            field=models.TextField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='edition_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='link_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='modify_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_year',
            field=models.IntegerField(default=2018),
        ),
        migrations.AlterField(
            model_name='item',
            name='publisher',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_file_database',
            field=models.TextField(max_length=255, null=True, verbose_name='Sub file/database'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
