# Generated by Django 2.0.3 on 2018-03-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0003_auto_20180321_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='claimant',
            field=models.CharField(choices=[('UF', 'University of Florida'), ('Available', 'Available'), ('Harvard', 'Harvard'), ('NC State', 'North Carolina State University'), ('Other1', 'Some other institutional partner(s)?')], default='Available', max_length=50, verbose_name='Purview'),
        ),
        migrations.AlterField(
            model_name='item',
            name='edition_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='place_of_publication',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='publisher',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_file_database',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Sub file/database'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
