# Generated by Django 2.0.3 on 2018-03-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0004_auto_20180321_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='accession_id',
            field=models.CharField(default='unique accession identifier', max_length=255, unique=True),
        ),
    ]
