# Generated by Django 2.0.3 on 2018-03-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0004_auto_20180323_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='agent',
            field=models.CharField(blank=True, choices=[('UF', 'University of Florida'), ('Available', 'Available'), ('Harvard', 'Harvard'), ('NC State', 'North Carolina State University'), ('Other1', 'Some other institutional partner(s)?')], default='Available', max_length=50, verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='item',
            name='holding',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='pmcid',
            field=models.TextField(blank=True, default='', verbose_name='PMCID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='reference_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
