# Generated by Django 2.0.2 on 2018-03-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0005_item_accession_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='claimant',
        ),
        migrations.AddField(
            model_name='item',
            name='agent',
            field=models.CharField(choices=[('UF', 'University of Florida'), ('Available', 'Available'), ('Harvard', 'Harvard'), ('NC State', 'North Carolina State University'), ('Other1', 'Some other institutional partner(s)?')], default='Available', max_length=50, verbose_name='Agent'),
        ),
    ]
