# Generated by Django 2.0.3 on 2018-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0005_auto_20180323_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='agent',
            field=models.CharField(blank=True, choices=[('UF', 'University of Florida'), ('Available', 'Available'), ('Harvard', 'Harvard'), ('NC State', 'North Carolina State University'), ('', 'Unavailable but unknown agent')], default='Available', max_length=50, verbose_name='Agent'),
        ),
    ]
