# Generated by Django 2.0.3 on 2018-03-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0006_auto_20180321_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='authors',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='place_of_publication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_file_database',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub file/database'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
