# Generated by Django 2.0.3 on 2018-03-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0009_auto_20180323_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='edition',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
