# Generated by Django 2.0.3 on 2018-03-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0010_auto_20180323_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='accession_number',
            field=models.CharField(default='Enter accession number here', max_length=255, unique=True),
        ),
    ]
