# Generated by Django 2.0.3 on 2018-03-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0011_auto_20180325_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='agent',
            field=models.CharField(blank=True, choices=[('UF', 'University of Florida'), ('Available', 'Available'), ('Harvard', 'Harvard'), ('NC State', 'North Carolina State University')], default='Available', help_text='Interested partner to verify or edit this item.', max_length=50, null=True, verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='item',
            name='agent_modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Parner Modify Date (UTC)'),
        ),
    ]
