# Generated by Django 2.0.3 on 2018-03-21 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='state_code',
        ),
    ]
