# Generated by Django 2.0.7 on 2018-10-15 14:33

from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0002_jp2batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='jp2batch',
            name='creating_username',
            field=maw_utils.SpaceCharField(db_index=True, default='', help_text='User who created this job to create Hathitrust jp2 packages.', max_length=255, verbose_name='User name'),
        ),
        migrations.AddField(
            model_name='jp2batch',
            name='end_datetime',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Importing DateTime (UTC)'),
        ),
        migrations.AddField(
            model_name='jp2batch',
            name='notes',
            field=maw_utils.SpaceTextField(blank=True, default='note', help_text='General notes about this batch job run', max_length=2550, null=True),
        ),
        migrations.AddField(
            model_name='jp2batch',
            name='process_id',
            field=models.IntegerField(default=0, help_text='Webserver job process id, if available.', null=True),
        ),
        migrations.AddField(
            model_name='jp2batch',
            name='result',
            field=maw_utils.SpaceTextField(blank=True, default='note', help_text='This result value may be set when the packages batch is completed. ', max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='jp2batch',
            name='batch_set',
            field=models.ForeignKey(default=2272, help_text='BatchSet for which to generate Hathitrust JP2 Packages', on_delete=django.db.models.deletion.CASCADE, to='dps.BatchSet'),
            preserve_default=False,
        ),
    ]
