# Generated by Django 2.0.3 on 2018-03-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0002_remove_item_state_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_index=True, default='RVP', max_length=64, verbose_name='Dept')),
                ('public', models.BooleanField(default=False, verbose_name='Public')),
                ('date_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='datetime')),
                ('topic', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sha512', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('up_name', models.CharField(default='tmpfile', max_length=128, verbose_name='up_name')),
                ('down_name', models.CharField(blank=True, default='tmpfile', max_length=128, null=True, verbose_name='down_name')),
                ('link_name', models.CharField(blank=True, default='click here', max_length=128, null=True, verbose_name='link_name')),
                ('size', models.IntegerField(default=0)),
                ('content_type', models.CharField(default='text/plain', max_length=128, verbose_name='content_type')),
                ('charset', models.CharField(blank=True, max_length=32, null=True, verbose_name='char_set')),
                ('url', models.CharField(default='tmpfile', max_length=256, verbose_name='url')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(db_index=True, default='RVP', max_length=255, verbose_name='Dept')),
                ('date_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='datetime')),
                ('url', models.CharField(default='tmpfile', max_length=255, verbose_name='url')),
                ('down_name', models.CharField(blank=True, default='tmpfile', max_length=255, null=True, verbose_name='down_name')),
                ('topic', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sha512', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('up_name', models.CharField(default='tmpfile', max_length=255, verbose_name='up_name')),
                ('size', models.IntegerField(default=0)),
                ('content_type', models.CharField(default='text/plain', max_length=255, verbose_name='content_type')),
                ('charset', models.CharField(blank=True, max_length=128, null=True, verbose_name='char_set')),
            ],
        ),
    ]
