# Generated by Django 2.0.3 on 2018-04-02 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0003_file_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_file',
            name='item_id',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='file',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hathitrust.Item'),
        ),
        migrations.DeleteModel(
            name='Item_file',
        ),
    ]
