# Generated by Django 2.0.2 on 2018-04-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0004_auto_20180402_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='location',
            field=models.FileField(default='hathitrust', upload_to='hathitrust/'),
            preserve_default=False,
        ),
    ]
