# Generated by Django 2.0.7 on 2018-10-16 12:10

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0005_remove_jp2batch_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jp2batch',
            name='result',
        ),
        migrations.AddField(
            model_name='jp2batch',
            name='status',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Save empty status to create packages. Check for status updates as packages are being built.', max_length=2550, null=True),
        ),
    ]
