# Generated by Django 2.0.7 on 2018-10-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0006_auto_20181016_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jp2batch',
            name='create_datetime',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Run Start DateTime (UTC)'),
        ),
    ]
