# Generated by Django 2.0.7 on 2018-10-17 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hathitrust', '0007_auto_20181016_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jp2batch',
            name='process_id',
        ),
        migrations.AddField(
            model_name='jp2batch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jp2batch',
            name='end_datetime',
            field=models.DateTimeField(editable=False, null=True, verbose_name='End DateTime (UTC)'),
        ),
        migrations.AlterField(
            model_name='jp2batch',
            name='status',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Status of ongoing or completed run. Check for status updates as packages are being built.', max_length=2550, null=True, verbose_name='Run Status'),
        ),
    ]
