# Generated by Django 2.0.4 on 2018-06-26 11:43

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0007_auto_20180625_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yaml',
            name='image_compression_agent',
            field=maw_utils.SpaceCharField(blank=True, help_text="Required if images were compressed before Submittal Item Package was generated. Eg, ImageMagick 6.7.8.<a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>More</a>", max_length=255),
        ),
    ]
