# Generated by Django 2.0.7 on 2018-10-17 12:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dps', '0035_auto_20181017_0835'),
        ('hathitrust', '0008_auto_20181017_0835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jp2Batch',
            new_name='Jp2Job',
        ),
        migrations.AlterModelOptions(
            name='jp2job',
            options={'verbose_name_plural': 'Jp2Jobes'},
        ),
    ]
