# Generated by Django 2.0.4 on 2018-06-26 11:58

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0008_auto_20180626_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='folder_path',
        ),
        migrations.AddField(
            model_name='item',
            name='bib_vid',
            field=models.CharField(default='XX12345678_12345', help_text='Bib_vid in format XX12345678_12345', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='yaml',
            name='bitonal_resolution_dpi',
            field=maw_utils.PositiveIntegerField(default=600, help_text="Required if images lack resolution information.<a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>More</a>"),
        ),
        migrations.AlterField(
            model_name='yaml',
            name='contone_resolution_dpi',
            field=maw_utils.PositiveIntegerField(default=600, help_text="Required if images lack resolution information.<a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>More</a>"),
        ),
        migrations.AlterField(
            model_name='yaml',
            name='image_compression_agent',
            field=maw_utils.SpaceCharField(blank=True, help_text="Required if images were compressed before Submittal Item Package was generated. Eg, ImageMagick 6.7.8. <a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>More</a>", max_length=255),
        ),
        migrations.AlterField(
            model_name='yaml',
            name='image_compression_date',
            field=models.DateTimeField(db_index=True, help_text="Required if images were compressed before Submittal Item Package was generated.<a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>More</a>"),
        ),
        migrations.AlterField(
            model_name='yaml',
            name='reading_order',
            field=maw_utils.SpaceCharField(choices=[('l2r', 'left-to-right'), ('r2l', 'right-to-left')], default='l2r', help_text="Example: use right-to-left ...<a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>More</a>", max_length=255),
        ),
        migrations.AlterField(
            model_name='yaml',
            name='scanning_order',
            field=maw_utils.SpaceCharField(choices=[('l2r', 'left-to-right'), ('r2l', 'right-to-left')], default='l2r', help_text="Either left-to-right or right-to-left... <a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>More</a>", max_length=255),
        ),
    ]
