# Generated by Django 2.0.4 on 2018-06-29 18:46

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0009_auto_20180626_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalbornyaml',
            name='creation_agent',
            field=maw_utils.SpaceCharField(help_text="Required: HathiTrust organization code who created digital file.<a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>More</a>", max_length=255),
        ),
        migrations.AlterField(
            model_name='digitalbornyaml',
            name='creation_datetime',
            field=models.DateTimeField(db_index=True, help_text="Required: Creation time of original file/item. Eg, PDF file's date. <a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>More</a>"),
        ),
        migrations.AlterField(
            model_name='digitalbornyaml',
            name='digital_content_provider',
            field=maw_utils.SpaceCharField(blank=True, help_text="Optional File-specific content provider's HathiTrust organization code. <a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>More</a>", max_length=255),
        ),
        migrations.AlterField(
            model_name='digitalbornyaml',
            name='tiff_artist',
            field=maw_utils.SpaceCharField(blank=True, help_text="Required if images lack TIFF Artist or XMP tiff:Artist header. <a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>More</a>", max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='bib_vid',
            field=models.CharField(default='AB12345678_12345', help_text='Bib_vid in format XX12345678_12345', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='printscanyaml',
            name='capture_datetime',
            field=models.DateTimeField(db_index=True, help_text="Date and time of original print scan, estimate OK. <a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>More</a>"),
        ),
        migrations.AlterField(
            model_name='printscanyaml',
            name='scanner_make',
            field=maw_utils.SpaceCharField(blank=True, default='CopiBook', help_text="<a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>Help</a>", max_length=255),
        ),
        migrations.AlterField(
            model_name='printscanyaml',
            name='scanner_model',
            field=maw_utils.SpaceCharField(default='', help_text="<a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>Help</a>", max_length=255),
        ),
        migrations.AlterField(
            model_name='printscanyaml',
            name='scanner_user',
            field=maw_utils.SpaceCharField(blank=True, default='UF Digtal Processing Services', help_text="<a  href='https://drive.google.com/file/d/0B0EHs5JWGUMLWjU2OHVhQzN5WEk/view'>Help</a>", max_length=255),
        ),
    ]
