# Generated by Django 2.0.7 on 2018-10-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0009_auto_20181017_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jp2job',
            options={'verbose_name_plural': 'Jp2Jobs'},
        ),
    ]
