# Generated by Django 2.0.4 on 2018-08-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0010_auto_20180629_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='packaged_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='selected_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='zip_md5',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
