# Generated by Django 2.1.2 on 2018-10-27 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dps', '0035_auto_20181017_0835'),
        ('hathitrust', '0011_auto_20181017_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsZip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('glob', maw_utils.SpaceCharField(default='', help_text='Glob file selector (Eg, *.* or *.jp2 or *.mets.xml, etc)', max_length=255)),
                ('create_datetime', models.DateTimeField(editable=False, null=True, verbose_name='Run Start DateTime (UTC)')),
                ('item_count', models.IntegerField(default=0, help_text='Number of bib_vid items zipped by this job.', null=True)),
                ('file_count', models.IntegerField(default=0, help_text='Total number of files zipped by this job.', null=True)),
                ('uncompressed_bytes', models.IntegerField(default=0, help_text='Total number of uncompressed bytes encodded in this zip file.', null=True)),
                ('compressed_bytes', models.IntegerField(default=0, help_text='Total number of compressed bytes encodded in this zip file.', null=True)),
                ('notes', maw_utils.SpaceTextField(blank=True, default='note', help_text='General notes about this batch job run', max_length=2550, null=True)),
                ('end_datetime', models.DateTimeField(editable=False, null=True, verbose_name='End DateTime (UTC)')),
                ('status', maw_utils.SpaceTextField(blank=True, default='', help_text='Status of ongoing or completed run. Check for status updates as packages are being built.', max_length=2550, null=True, verbose_name='Run Status')),
                ('batch_set', models.ForeignKey(help_text='BatchSet for which to generate a zip file of resource items', on_delete=django.db.models.deletion.CASCADE, to='dps.BatchSet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
