# Generated by Django 2.1.2 on 2018-11-28 14:31

from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0012_itemszip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemszip',
            name='glob',
            field=maw_utils.SpaceCharField(default='*.mets.xml', help_text='Glob file selector (Eg, *.* or *.jp2 or *.mets.xml, etc)', max_length=255),
        ),
        migrations.AlterField(
            model_name='jp2job',
            name='batch_set',
            field=models.ForeignKey(help_text='BatchSet to input to generate Hathitrust JP2 Packages', on_delete=django.db.models.deletion.CASCADE, to='dps.BatchSet'),
        ),
    ]
