# Generated by Django 2.1.2 on 2018-12-05 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hathitrust', '0013_auto_20181128_0931'),
        ('hathitrust', '0012_auto_20181108_1442'),
    ]

    operations = [
    ]
