# Generated by Django 2.0.4 on 2018-06-07 14:45

from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', maw_utils.SpaceCharField(default='', help_text='Unique name for this field for this output relation.', max_length=255)),
                ('type', maw_utils.SpaceCharField(default='string', help_text='Not fully implemented now. type string is assumed.', max_length=255, unique=True)),
                ('default', maw_utils.SpaceCharField(default='', help_text='Default value for this field.', max_length=255, unique=True)),
            ],
            options={
                'ordering': ['relation', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', maw_utils.SpaceCharField(default='', help_text="Unique name for this snowflake genre. Please include a version label suffix like 'V1.0'.", max_length=255, unique=True)),
                ('create_datetime', models.DateTimeField(auto_now=True, help_text='Creation DateTime', null=True)),
                ('notes', maw_utils.SpaceTextField(default='', help_text='Notes on this snowflake genre. What is it used for?', max_length=2550)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', maw_utils.SpaceCharField(default='', help_text='Unique name for this relation for this genre.', max_length=255)),
                ('child_name', maw_utils.SpaceCharField(default='', help_text='Name this relation or element relative to others or its parent. ', max_length=255, unique=True)),
                ('min_occurs', models.IntegerField(default=True, help_text='Minimum rows required with this parent.')),
                ('max_occurs', models.IntegerField(default=True, help_text='Maximum rows required with this parent.')),
                ('notes', maw_utils.SpaceTextField(default='', help_text='Notes on this instance.', max_length=2550)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snow.Genre')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snow.Relation')),
            ],
            options={
                'ordering': ['genre', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', maw_utils.SpaceCharField(default='', help_text='Unique name for this field for this output relation.', max_length=255)),
                ('notes', maw_utils.SpaceTextField(default='', help_text='Notes on this instance.', max_length=2550)),
                ('values_set_name', maw_utils.SpaceCharField(blank=True, default=None, help_text="Name of a values_set with the related field's allowed values.", max_length=255, null=True, unique=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snow.Field')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snow.Relation'),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('genre', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('relation', 'name')},
        ),
    ]
