# Generated by Django 2.0.4 on 2018-06-07 17:51

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='type',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='child_name',
        ),
        migrations.AddField(
            model_name='field',
            name='max_length',
            field=maw_utils.PositiveIntegerField(default=255, help_text='Maximum number of characters in this field.'),
        ),
        migrations.AddField(
            model_name='relation',
            name='local_name',
            field=maw_utils.SpaceCharField(default='', help_text='Unique name for this relation among those with the same parent. Eg, an xml element name for some uses.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=maw_utils.SpaceCharField(default='', help_text='Unique name for this field under this relation.', max_length=255),
        ),
        migrations.AlterField(
            model_name='relation',
            name='max_occurs',
            field=maw_utils.PositiveIntegerField(default=True, help_text='Maximum occurrences required under this parent.'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='min_occurs',
            field=maw_utils.PositiveIntegerField(default=True, help_text='Minimum occurrences required under this parent.'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=maw_utils.SpaceCharField(default='', help_text='Unique name for this relation under this genre.', max_length=255),
        ),
        migrations.AlterField(
            model_name='relation',
            name='notes',
            field=maw_utils.SpaceTextField(default='', help_text='Notes on this relation.', max_length=2550),
        ),
    ]
