# Generated by Django 2.0.4 on 2018-06-11 18:06

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='max_occurs',
            field=models.IntegerField(default=0, help_text='Maximum occurrences required under this parent. 0 or null here means unbounded.'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='min_occurs',
            field=maw_utils.PositiveIntegerField(default=0, help_text='Minimum occurrences required under this parent.'),
        ),
    ]
