# Generated by Django 2.0.4 on 2018-06-11 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0002_auto_20180611_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relation',
            name='local_name',
        ),
        migrations.AlterField(
            model_name='relation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='snow.Relation', verbose_name='Parent relation'),
        ),
    ]
