# Generated by Django 2.0.4 on 2018-06-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0002_auto_20180615_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='schema',
        ),
    ]
