# Generated by Django 2.0.4 on 2018-06-07 19:01

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0002_auto_20180607_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='name',
            field=maw_utils.SpaceCharField(default='', help_text='Unique name for this field under this relation.', max_length=255, verbose_name='Field name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=maw_utils.SpaceCharField(default='', help_text="Unique name for this snowflake genre. Please include a version label suffix like 'V1.0'.", max_length=255, unique=True, verbose_name='Genre name'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='notes',
            field=maw_utils.SpaceTextField(default='', help_text='(1) Used for? (2) based on? Newlines are discarded, so use (1), (2), etc, labels for notes.', max_length=2550),
        ),
        migrations.AlterField(
            model_name='relation',
            name='max_occurs',
            field=models.IntegerField(default=0, help_text='Maximum occurrences required under this parent. 0 or null means no limit.'),
        ),
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=maw_utils.SpaceCharField(default='', help_text='Unique name for this relation under this genre.', max_length=255, verbose_name='Relation name'),
        ),
    ]
