# Generated by Django 2.0.4 on 2018-06-07 19:05

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0003_auto_20180607_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='notes',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='(1) Used for? (2) based on? Newlines are discarded, so use (1), (2), etc, labels for notes.', max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='notes',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Notes on this relation.', max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='restriction',
            name='notes',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Notes on this instance.', max_length=2550, null=True),
        ),
    ]
