# Generated by Django 2.0.4 on 2018-06-12 16:57

from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0003_auto_20180611_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', maw_utils.SpaceCharField(default='', help_text='Unique name for this relation under this schema.', max_length=255, verbose_name='Relation name')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='snow.Element', verbose_name='Parent relation')),
                ('schema', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='snow.Schema')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
