# Generated by Django 2.0.4 on 2018-06-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0003_remove_node_schema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchset',
            name='field',
        ),
        migrations.RemoveField(
            model_name='batchset',
            name='snow_node',
        ),
        migrations.RemoveField(
            model_name='batchset',
            name='vocabulary',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='batch_set',
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('parent', 'name')},
        ),
        migrations.DeleteModel(
            name='BatchSet',
        ),
    ]
