# Generated by Django 2.0.4 on 2018-06-07 19:08

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0004_auto_20180607_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='default',
            field=maw_utils.SpaceCharField(blank=True, default='', help_text='Default value for this field.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='max_length',
            field=maw_utils.PositiveIntegerField(blank=True, default=255, help_text='Maximum number of characters in this field.', null=True),
        ),
    ]
