# Generated by Django 2.0.4 on 2018-06-07 19:12

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0005_auto_20180607_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='local_name',
            field=maw_utils.SpaceCharField(default='', help_text='Unique name for this relation among those with the same parent. Eg, an xml element name for some uses.', max_length=255),
        ),
    ]
