# Generated by Django 2.0.4 on 2018-06-18 14:09

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0005_auto_20180618_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchset',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='batchset',
            name='snow_node',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='batch_set',
        ),
        migrations.AlterField(
            model_name='batch',
            name='creator_role',
            field=maw_utils.SpaceCharField(default='', help_text='Name for this creator role.It will be read-only in produciton.', max_length=255, unique=True, verbose_name='Creator Role'),
        ),
        migrations.DeleteModel(
            name='BatchSet',
        ),
    ]
