# Generated by Django 2.0.4 on 2018-06-12 19:24

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0005_auto_20180612_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='max_occurs',
            field=models.IntegerField(default=0, help_text='Maximum occurrences required under this parent. 0 or null here means unbounded.'),
        ),
        migrations.AddField(
            model_name='node',
            name='min_occurs',
            field=maw_utils.PositiveIntegerField(default=0, help_text='Minimum occurrences required under this parent.'),
        ),
        migrations.AddField(
            model_name='node',
            name='notes',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Notes on this relation.', max_length=2550, null=True),
        ),
    ]
