# Generated by Django 2.0.4 on 2018-06-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0006_auto_20180607_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relation',
            options={'ordering': ['genre', 'id']},
        ),
    ]
