# Generated by Django 2.0.4 on 2018-06-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0006_auto_20180618_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
    ]
