# Generated by Django 2.0.4 on 2018-06-18 14:25

from django.db import migrations, models
import django.db.models.deletion
import maw_utils
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0007_auto_20180618_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', maw_utils.SpaceCharField(default='', help_text='Unique name for this batchSet, include owning org for now.', max_length=255)),
                ('create_datetime', models.DateTimeField(auto_now=True, help_text='Creation DateTime', null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='snow.BatchSet', verbose_name='Parent relation')),
                ('snow_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snow.Node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
