# Generated by Django 2.0.4 on 2018-06-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0007_auto_20180607_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='default',
        ),
        migrations.AddField(
            model_name='field',
            name='is_required',
            field=models.NullBooleanField(default=False, help_text='Whether this field is required in a genre instance.'),
        ),
    ]
