# Generated by Django 2.0.4 on 2018-06-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0008_batchset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchset',
            name='level',
        ),
        migrations.RemoveField(
            model_name='batchset',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='batchset',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='batchset',
            name='tree_id',
        ),
    ]
