# Generated by Django 2.0.4 on 2018-06-08 16:24

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0009_auto_20180608_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='type',
            field=maw_utils.SpaceTextField(blank=True, default=2550, help_text='Maximum number of characters in this field.', null=True),
        ),
    ]
