# Generated by Django 2.0.4 on 2018-06-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0010_batch_batch_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchset',
            name='parent',
        ),
    ]
