# Generated by Django 2.0.4 on 2018-06-08 18:26

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0011_auto_20180608_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regex',
            options={'verbose_name_plural': 'Regexes'},
        ),
        migrations.AlterModelOptions(
            name='vocabulary',
            options={'verbose_name_plural': 'Vocabularies'},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word']},
        ),
        migrations.AddField(
            model_name='regex',
            name='regex',
            field=maw_utils.SpaceCharField(default='', help_text='Unique name for this field for this output relation.', max_length=255),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=maw_utils.SpaceCharField(default='', help_text='A word in this vocabulary.', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('vocabulary', 'word')},
        ),
    ]
