# Generated by Django 2.0.4 on 2018-06-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0011_remove_batchset_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='creator_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snow.Role'),
        ),
    ]
