# Generated by Django 2.0.4 on 2018-06-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0012_auto_20180618_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_set',
        ),
    ]
