# Generated by Django 2.0.4 on 2018-06-18 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0013_remove_batch_batch_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snow.BatchSet'),
        ),
    ]
