# Generated by Django 2.0.4 on 2018-06-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0014_batch_batch_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='item_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='received_imported_items',
            field=models.BooleanField(default=False, editable=False, help_text='Whether this batch has received imported items.'),
        ),
    ]
