# Generated by Django 2.0.4 on 2018-06-19 14:31

from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('snow', '0015_auto_20180618_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchset',
            options={'verbose_name': 'Structured Batch', 'verbose_name_plural': 'Structured Batches'},
        ),
        migrations.AddField(
            model_name='attribute',
            name='notes',
            field=maw_utils.SpaceTextField(blank=True, default='', help_text='Notes', max_length=5555, null=True),
        ),
        migrations.AlterField(
            model_name='batchset',
            name='snow_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snow.Node', verbose_name='Batch Root Node'),
        ),
    ]
