# Generated by Django 2.0.2 on 2018-03-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0002_auto_20180322_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='doi',
            field=models.TextField(blank=True, default='', verbose_name='DOI'),
        ),
        migrations.AlterField(
            model_name='item',
            name='edition_url',
            field=models.URLField(blank=True, null=True, verbose_name='Edition_URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='link_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link_URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pmcid',
            field=models.TextField(blank=True, default='', verbose_name='PCMID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pmid',
            field=models.TextField(blank=True, default='', verbose_name='PMID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_1',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_10',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_11',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_12',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_13',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_14',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_15',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_2',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_3',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_4',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_5',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_6',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_7',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_8',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='user_9',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
