# Generated by Django 2.0.3 on 2018-03-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0008_auto_20180323_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='accession_number',
            field=models.CharField(default='unique accession number', max_length=255),
        ),
    ]
