# Generated by Django 2.0.2 on 2018-04-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0013_auto_20180402_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='agent_modify_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modify Date (UTC)'),
        ),
    ]
