# Generated by Django 2.0.4 on 2018-06-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0015_auto_20180611_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('IP', 'In Process'), ('DZ', 'Digitized')], default='', help_text='Status of processing for this item.', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
