# Generated by Django 2.0.4 on 2018-08-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0019_auto_20180806_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='agent',
            field=models.CharField(blank=True, choices=[('UF', 'University of Florida'), ('Available', 'Available'), ('Harvard', 'Harvard'), ('UNC', 'University of North Carolina at Chapel Hill')], default='Available', help_text='Partner to verify or edit this item.', max_length=50, null=True, verbose_name='Partner'),
        ),
    ]
