# Generated by Django 2.0.4 on 2018-08-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0021_auto_20180820_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='agent',
            field=models.CharField(blank=True, choices=[('UF', 'University of Florida'), ('HVD', 'Harvard'), ('UNC', 'University of North Carolina at Chapel Hill'), ('-', '-')], default='-', help_text='Partner who claimed to verify or edit this item.', max_length=50, verbose_name='Claimed'),
        ),
    ]
