# Generated by Django 2.0.4 on 2018-08-23 21:56

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0023_auto_20180821_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='holding',
            field=maw_utils.SpaceCharField(blank=True, choices=[('FQG', 'University of Miami'), ('FXG', 'Florida International'), ('FUG', 'University of Florida'), ('HLS', 'Harvard'), ('NDD', 'Duke University'), ('NOC', 'U of North Carolina'), ('NYP', 'New York Public')], default='', editable=False, max_length=255),
        ),
    ]
