# Generated by Django 2.0.4 on 2018-08-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0024_auto_20180823_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='agent',
            field=models.CharField(blank=True, choices=[('-', '-'), ('UF', 'University of Florida'), ('HVD', 'Harvard'), ('UNC', 'U of North Carolina'), ('UMI', 'University of Miami'), ('FIU', 'Florida International'), ('DUKE', 'Duke University'), ('NYP', 'New York Public')], default='-', help_text='Partner who claimed to verify or edit this item.', max_length=50, verbose_name='Claimed'),
        ),
    ]
