# Generated by Django 2.0.4 on 2018-08-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0026_auto_20180823_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='agent',
            field=models.CharField(blank=True, choices=[('-', '-'), ('DUKE', 'Duke University'), ('FIU', 'Florida International'), ('HVD', 'Harvard'), ('NYP', 'New York Public'), ('UF', 'University of Florida'), ('UMI', 'University of Miami'), ('UNC', 'U of North Carolina')], default='-', help_text='Partner who claimed to verify or edit this item.', max_length=50, verbose_name='Claimed'),
        ),
    ]
