# Generated by Django 2.0.7 on 2018-09-13 20:05

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0028_auto_20180824_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status_notes',
            field=maw_utils.SpaceTextField(blank=True, default='', null=True),
        ),
    ]
