# Generated by Django 2.0.7 on 2018-09-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0029_item_status_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='accession_number',
            field=models.CharField(default='Enter accession number here', max_length=255, unique=True, verbose_name='OCLC accession number'),
        ),
        migrations.AlterField(
            model_name='item',
            name='agent',
            field=models.CharField(blank=True, choices=[('-', '-'), ('DUKE', 'Duke University'), ('FIU', 'Florida International'), ('HVD', 'Harvard'), ('NYP', 'New York Public'), ('UF', 'University of Florida'), ('UMI', 'University of Miami'), ('UNC', 'U of North Carolina')], default='-', help_text="Partner who claimed this item via an 'Action:' on the parent 'Items' web page.", max_length=50, verbose_name='Claimed'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, choices=[('', '-'), ('PG', 'Pending'), ('IP', 'In Process'), ('DZ', 'Digitized')], default='', help_text='Status of processing for this item.', max_length=50, verbose_name='Status'),
        ),
    ]
