# Generated by Django 2.0.7 on 2018-09-20 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0030_auto_20180917_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='Institution name')),
                ('name20', models.CharField(default='', help_text='Short Institution name with a maximum of 20 characters.', max_length=20, unique=True, verbose_name='Short Name')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='institution',
            field=models.ForeignKey(blank=True, help_text="Institution that claimed this item via an 'Action:' on the parent 'Items' web page.", null=True, on_delete=django.db.models.deletion.CASCADE, to='cuba_libro.Item'),
        ),
    ]
