# Generated by Django 2.0.7 on 2018-09-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0031_auto_20180920_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='institution',
            field=models.ForeignKey(blank=True, help_text="Institution that claimed this item via an 'Action:' on the parent 'Items' web page.", null=True, on_delete=django.db.models.deletion.CASCADE, to='cuba_libro.Institution'),
        ),
    ]
