# Generated by Django 2.0.7 on 2018-09-20 12:27

from django.db import migrations
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0032_auto_20180920_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='notes',
            field=maw_utils.SpaceTextField(blank=True, default='', null=True),
        ),
    ]
