# Generated by Django 2.1.2 on 2018-10-23 22:31

from django.db import migrations, models
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0032_auto_20180920_0813'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='item',
            name='institution',
        ),
        migrations.AddField(
            model_name='institution',
            name='notes',
            field=maw_utils.SpaceTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='agent',
            field=models.CharField(blank=True, db_index=True, help_text="Institution that claimed this item via an 'Action:' on the parent 'Items' web page.", max_length=255, null=True, verbose_name='Institution'),
        ),
    ]
