# Generated by Django 2.1.2 on 2018-10-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0033_auto_20181023_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='agent',
        ),
    ]
