# Generated by Django 2.1.2 on 2018-10-24 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maw_utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuba_libro', '0035_item_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', maw_utils.SpaceTextField(default='Some note here.', help_text='Optional note.')),
                ('agent', models.ForeignKey(blank=True, help_text='Institution that this user is affiliated with.', null=True, on_delete=django.db.models.deletion.CASCADE, to='cuba_libro.Institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
