# Generated by Django 2.1.2 on 2018-10-24 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0036_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='agent',
            field=models.ForeignKey(default=1, help_text='Institution that this user is affiliated with.', on_delete=django.db.models.deletion.CASCADE, to='cuba_libro.Institution'),
            preserve_default=False,
        ),
    ]
