# Generated by Django 2.1.2 on 2018-10-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0038_profile2'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='link_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link_URL'),
        ),
    ]
