# Generated by Django 2.1.2 on 2018-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0039_institution_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile2',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='profile2',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='default', help_text='username of MAW user who is authorized to use the Cuba Libro Datbase.', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile2',
        ),
    ]
