# Generated by Django 2.1.2 on 2018-10-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuba_libro', '0040_auto_20181024_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='oclc_name',
            field=models.CharField(blank=True, default='', help_text='Optional Code used by OCLC for this Institution with a maximum of 20 characters.', max_length=20, verbose_name='OCLC name'),
        ),
    ]
