# Generated by Django 2.0.2 on 2018-04-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about this project and related info free form.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_investigator',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
