# Generated by Django 2.0.3 on 2018-04-11 18:27

from django.db import migrations
import lcroyster.models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0002_auto_20180411_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=lcroyster.models.SpaceTextField(blank=True, help_text='Notes about the location', max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='co_principal_investigators',
            field=lcroyster.models.SpaceTextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='collaborators',
            field=lcroyster.models.SpaceTextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=lcroyster.models.SpaceTextField(blank=True, help_text='Notes about this project and related info in free form.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='principal_investigators',
            field=lcroyster.models.SpaceTextField(blank=True, help_text='Usually this is a single investigator, but some sponsors like NSF allow multiple principal investigators', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='notes',
            field=lcroyster.models.SpaceTextField(blank=True, help_text='More notes about the sensor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensordeploy',
            name='notes',
            field=lcroyster.models.SpaceTextField(blank=True, help_text='Notes about the deployment', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensorservice',
            name='notes',
            field=lcroyster.models.SpaceTextField(blank=True, help_text='Notes about the deployment\nISSUE: Dropped download_time, next_download,measurements_downloaded, project, site, lat, lon, manufacurer, type date_deployed, time_started, and redeployed because this is coverd by water_observations, service_datetime and sensor_deploy data.', max_length=255, null=True),
        ),
    ]
