# Generated by Django 2.0.2 on 2018-04-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0002_auto_20180407_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='status_observation_date',
            new_name='status_observation_datetime',
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='meters_above_seafloor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
