# Generated by Django 2.0.2 on 2018-04-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0002_auto_20180408_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='serial_number',
            field=models.CharField(blank=True, help_text='For example: VNNNN for a vanEssen:diver sensor or simply NNNN for a Star-Oddi:CT sensor. For example, one vanEssen:Diver sensor serial number is V5602 and one Star-Oddi:CT serial number is 8814.', max_length=150, null=True),
        ),
    ]
