# Generated by Django 2.0.2 on 2018-04-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0003_auto_20180407_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='observation_period_unit_count',
            field=models.CharField(blank=True, help_text='The typical number of observation period units between observations or readings.', max_length=50, null=True),
        ),
    ]
