# Generated by Django 2.0.3 on 2018-04-12 12:22

from django.db import migrations
import lcroyster.models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0003_auto_20180411_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='alias1',
            field=lcroyster.models.SpaceCharField(blank=True, help_text='Alternative name designation of the location', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='alias2',
            field=lcroyster.models.SpaceCharField(blank=True, default=None, help_text='Alternative name designation of the location', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=lcroyster.models.SpaceCharField(blank=True, help_text='Location name, eg LCR Buoy One.', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_investigator',
            field=lcroyster.models.SpaceCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='department_id',
            field=lcroyster.models.SpaceCharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=lcroyster.models.SpaceCharField(help_text='Long name for this project', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_website_code',
            field=lcroyster.models.SpaceCharField(help_text='Short unique code for this project (up to 16 characters)', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='proposal_id',
            field=lcroyster.models.SpaceCharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible_unit',
            field=lcroyster.models.SpaceCharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sponsor_names',
            field=lcroyster.models.SpaceCharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sponsors_award_id',
            field=lcroyster.models.SpaceCharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uf_award_id',
            field=lcroyster.models.SpaceCharField(blank=True, help_text='This field should normally start AWD and followed by 5 digits.', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='serial_number',
            field=lcroyster.models.SpaceCharField(blank=True, help_text='For example: VNNNN for a vanEssen:diver sensor or simply NNNN for a Star-Oddi:CT sensor. For example, one vanEssen:Diver sensor serial number is V5602 and one Star-Oddi:CT serial number is 8814.', max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sensorservice',
            name='color_tape',
            field=lcroyster.models.SpaceCharField(blank=True, help_text='ISSUE: Is this (1) the tape color found at start of service, or (2) the color of tape applied to this sensor during service?', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='manufacturer',
            field=lcroyster.models.SpaceCharField(blank=True, help_text='For example: vanEssen or Star-Oddi.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='model_type',
            field=lcroyster.models.SpaceCharField(help_text='For example: vanEssen usually has type Diver, and Star-Oddi usually has type CT. ', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='waterobservation',
            name='note',
            field=lcroyster.models.SpaceCharField(blank=True, help_text='Short note on observation, 32 characters or less.', max_length=32, null=True),
        ),
    ]
