# Generated by Django 2.0.2 on 2018-04-08 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0003_auto_20180408_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordeploy',
            name='meters_above_seafloor',
        ),
        migrations.AddField(
            model_name='sensorservice',
            name='measurements_downloaded',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='alias1',
            field=models.CharField(blank=True, help_text='Alternative name designation of the location', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='alias2',
            field=models.CharField(blank=True, help_text='Alternative name designation of the location', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, help_text='Location name, eg LCR Buoy One.', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about the location', max_length=2550, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='location',
            field=models.ForeignKey(blank=True, help_text='This field is reserved to report the most recent deployed location of this sensor. Value 0 or Null means sensor not in service.Unless and until a new database view is implemented, this field is reserved to be updated automatically by some program when table sensor_deploy is updated, so manual edits could be overwritten', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lcroyster.Location'),
        ),
        migrations.AlterField(
            model_name='sensorservice',
            name='battery_life_remaining_percent',
            field=models.IntegerField(blank=True, help_text='Enter an integer from 0 to 100.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('sensor_type', 'serial_number')},
        ),
    ]
