# Generated by Django 2.0.3 on 2018-04-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0004_auto_20180408_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='alias2',
            field=models.CharField(blank=True, default=None, help_text='Alternative name designation of the location', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='tile_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
