# Generated by Django 2.0.3 on 2018-04-12 13:46

from django.db import migrations, models
import lcroyster.models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0004_auto_20180412_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='alias1',
            field=lcroyster.models.SpaceCharField(blank=True, default=None, help_text='Alternative name designation of the location', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=lcroyster.models.SpaceCharField(blank=True, default='name', help_text='Location name, eg LCR Buoy One.', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='serial_number',
            field=lcroyster.models.SpaceCharField(blank=True, help_text='Our own abbreviated serials numbers. Use VNNNN for a vanEssen:diver sensor (e.g., V6502) or SNNNN for a Star-Oddi:CT sensor. For a Sea-Bird sensor, use BNNNN. ', max_length=150, null=True, unique=True),
        ),
    ]
