# Generated by Django 2.0.2 on 2018-04-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0004_auto_20180407_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='meters_above_seafloor',
        ),
        migrations.RemoveField(
            model_name='sensordeploy',
            name='testint',
        ),
        migrations.AddField(
            model_name='sensordeploy',
            name='meters_above_seafloor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
