# Generated by Django 2.0.3 on 2018-04-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0005_auto_20180409_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='tile_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
