# Generated by Django 2.0.3 on 2018-04-26 16:01

from django.db import migrations, models
import django.db.models.deletion
import lcroyster.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0005_auto_20180412_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuoyObservation',
            fields=[
                ('buoy_observation_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('observation_datetime', models.DateTimeField(blank=True, null=True)),
                ('in_service', models.IntegerField(blank=True, null=True)),
                ('pressure_cm', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('conductivity_ms_cm', models.FloatField(blank=True, db_column='conductivity_mS_cm', null=True)),
                ('salinity_psu', models.FloatField(blank=True, null=True)),
                ('sound_velocity_m_sec', models.FloatField(blank=True, null=True)),
                ('note', lcroyster.models.SpaceCharField(blank=True, help_text='Short note on observation, 32 characters or less.', max_length=32, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lcroyster.Location')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lcroyster.Sensor')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='buoyobservation',
            unique_together={('sensor', 'observation_datetime')},
        ),
    ]
