# Generated by Django 2.0.3 on 2018-04-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0006_auto_20180409_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact_investigator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='department_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsible_unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sponsors_award_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uf_award_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='battery_expiration_date',
            field=models.DateField(blank=True, default='2019-08-11', null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='initial_deployment_datetime',
            field=models.DateTimeField(blank=True, default='2017-08-11 12:00:00', help_text='Datetime of initial employment.', null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='manufacture_date',
            field=models.DateField(blank=True, default='2016-08-11', null=True),
        ),
    ]
