# Generated by Django 2.0.3 on 2018-04-09 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0007_auto_20180409_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='range_high_mS_cm',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='range_low_mS_cm',
        ),
    ]
