# Generated by Django 2.0.4 on 2018-04-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0007_auto_20180426_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buoyobservation',
            name='observation_datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
