# Generated by Django 2.0.2 on 2018-05-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0008_auto_20180427_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterobservation',
            name='salinity_psu_calculated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterobservation',
            name='observation_datetime',
            field=models.DateTimeField(blank=True, default='2001-01-01'),
            preserve_default=False,
        ),
    ]
