# Generated by Django 2.0.3 on 2018-04-11 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0008_auto_20180409_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='battery_expiration_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 11, 7, 52, 27, 977006), null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='initial_deployment_datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 4, 11, 7, 52, 27, 977006), help_text='Datetime of initial employment.', null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='manufacture_date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 11, 7, 52, 27, 977006), null=True),
        ),
    ]
