# Generated by Django 2.0.2 on 2018-05-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0009_auto_20180518_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='buoyobservation',
            name='salinity_psu_calculated',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
