# Generated by Django 2.0.3 on 2018-04-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0009_auto_20180411_0752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'ordering': ['sensor_type']},
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='initial_deployment_datetime',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='location',
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='Long name for this project', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(help_text='Short unique code for this project (up to 10 characters)', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='battery_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='manufacture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
