# Generated by Django 2.0.3 on 2018-04-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0010_auto_20180411_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact_investigator',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='proposal_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sponsors_award_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='uf_award_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
