# Generated by Django 2.0.3 on 2018-04-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0011_auto_20180411_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_website_code',
            field=models.CharField(default='First', help_text='Short unique code for this project (up to 10 characters)', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_investigator',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='uf_award_id',
            field=models.CharField(blank=True, help_text='This field should normally start AWD and followed by 5 digits.', max_length=200, null=True, unique=True),
        ),
    ]
