# Generated by Django 2.0.3 on 2018-04-11 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0012_auto_20180411_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_website_code',
        ),
    ]
