# Generated by Django 2.0.3 on 2018-04-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lcroyster', '0013_remove_project_project_website_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_website_code',
            field=models.CharField(default='First', help_text='Short unique code for this project (up to 16 characters)', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
